// AppointmentVitals styles
import { Platform, StyleSheet } from 'react-native';
import { COLORS, FONTS, SIZES } from '../constants';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
import { isHpTablet } from '../hooks/useDeviceCheck';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.white,
  },
  header: {
    justifyContent: 'center',
    paddingVertical: isHpTablet(1),
    borderBottomColor: COLORS.white_smoke,
    borderBottomWidth: 1,
  },
  topBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: hp('1.5%'),
    paddingVertical: hp('0.7%'),
  },
  sectionContainer: {
    paddingVertical: hp('0.5%'),
    paddingHorizontal: hp('2%'),
  },
  section: {
    ...FONTS.text,
  },
  messageText: {
    ...FONTS.text,
    fontSize: isHpTablet('1.2%'),
    textAlign: 'center',
  },
  sectionBorderStyle: {
    borderBottomColor: COLORS.black,
    borderBottomWidth: 3,
    width: '30%',
  },
  noAppointment: {
    height: SIZES.screenHeight / 1.25,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  appointmentContainer: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
  },
  name: {
    fontFamily: FONTS.SFProDisplayRegular,
    color: COLORS.black_252525,
    fontSize: isHpTablet('2%'),
  },
  nameArrow: { marginTop: hp('0.3%'), marginStart: SIZES.base },
  filterIcon: { alignItems: 'center', height: 14, width: 14 },
  line: {
    borderBottomColor: COLORS.grey,
    borderBottomWidth: 1,
  },
  filterText: {
    marginStart: hp('2%'),
    marginTop: hp('1.5%'),
    fontSize: hp('1.4%'),
    color: COLORS.text,
    fontWeight: '500',
    fontFamily: FONTS.SFProDisplayMedium,
  },
  filterValue: {
    marginTop: hp('1.5%'),
    fontSize: hp('1.4%'),
    color: COLORS.text,
    fontWeight: '500',
    fontFamily: FONTS.SFProDisplayRegular,
  },
  backgroundStyle: {
    backgroundColor: COLORS.white,
    borderColor: COLORS.gray,
    borderWidth: 2,
  },
  accountIconStyle: {
    marginTop: hp('0.5%'),
    // marginHorizontal: 5,
    marginRight: hp('0.5%'),
    alignSelf: 'center',
  },
  accNameStyle: {
    marginTop: hp('0.5%'),
    fontSize: hp('1.6%'),
    fontWeight: '500',
  },
  imageTouchStyle: {
    justifyContent: 'center',
  },
  viewStyle: {
    marginTop: hp('1.5%'),
  },
  clearText: {
    fontFamily: FONTS.Inter,
    fontSize: hp('1.4%'),
    fontWeight: '500',
    marginTop: hp('1.5%'),
    color: COLORS.text,
    marginHorizontal: hp('1%'),
  },
  labBkarStyle: {
    margin: hp('2%'),
  },
  testNameStyle: {
    color: COLORS.black_121212,
    fontSize: isHpTablet('1.8%'),
    fontFamily: FONTS.SFProDisplaySemibold,
    fontWeight: '600',
    lineHeight: hp('2%'),
    marginBottom: hp('1%'),
  },
  testTypeStyle: {
    color: COLORS.background.primary,
    fontSize: hp('1.5%'),
    fontWeight: '400',
    fontFamily: FONTS.SFProDisplayRegular,
    lineHeight: hp('1.6%'),
  },
  deleteIcon: { width: hp('2.5%'), height: hp('2.7%'), marginHorizontal: hp('1%') },
  divider: {
    borderBottomWidth: 1,
    borderColor: COLORS.grey_E5E5E5,
  },
  labBkarBoxStyle: {
    marginHorizontal: hp('1%'),
    marginVertical: hp('2%'),
    borderRadius: hp('0.5%'),
    width: hp('7%'),
    height: hp('7%'),
  },
  contentContainerStyle: {
    width: '100%',
    paddingHorizontal: hp('2%'),
  },
  commonStyle: {
    height: hp('2.5%'),
    width: wp('22%'),
  },
  secondWidth: {
    width: wp('60%'),
  },
  thirdWidth: {
    width: wp('10%'),
  },
  boxMainContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: hp('3%'),
    paddingVertical: hp('2%'),
    backgroundColor: COLORS.background.white,
    borderBottomWidth: 1,
    borderRadius: hp('1%'),
    borderBottomColor: '#E2EEFF',
    shadowColor: COLORS.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: Platform.OS === 'ios' ? 0.02: 0.2,
    shadowRadius: 4,
    elevation: 2,
    marginVertical: hp('1%'),
  },
  investigationText: {
    fontFamily: FONTS.SFProDisplaySemibold,
    fontSize: hp('5%'),
    lineHeight: hp('1.8%'),
    color: COLORS.background.primary,
  },
  testListContainer: {
    height: hp('20%'),
  },
  testListDivider: {
    borderBottomWidth: 1,
    borderColor: COLORS.grey_E5E5E5,
    marginTop: hp('0.5%'),
  },
  addIcon: {
    height: 22,
    width: 22,
    justifyContent: 'center',
  },
  unit: {
    color: '#17CF9D',
    fontSize: isHpTablet('1.8%'),
    fontWeight: '500',
    fontFamily: FONTS.SFProDisplaySemibold,
  },
  unitText: {
    fontFamily: FONTS.SFProDisplayMedium,
    fontSize: isHpTablet('1.5%'),
    color: '#9A9FA4',
  },
  date: {
    color: '#8A8A8A',
    fontSize: 12,
    fontWeight: '600',
    paddingTop: '1%',
  },
  searchInput: {
    width: '100%',
    height: isHpTablet('5.2%'),
    marginVertical: 5,
    backgroundColor: 'white',
    fontSize: isHpTablet('1.6%'),
    fontWeight: '500',
    fontFamily: FONTS.SFProDisplayMedium,
    lineHeight: isHpTablet('1.8%'),
  },
  searchIcon: { marginTop: hp('1.5%') },
  observationText: {
    fontFamily: FONTS.SFProDisplaySemibold,
    fontSize: isHpTablet('1.8%'),
    lineHeight: isHpTablet('2%'),
    color: '#232323',
    marginHorizontal: isHpTablet('2.8%'),
    marginBottom: isHpTablet('1%'),
  },
  chipLabelBox: {
    position: 'absolute',
    backgroundColor: 'transparent',
    left: 6,
    top: 18,
    paddingStart: 5,
    paddingEnd: 5,
    paddingHorizontal: 1,
    zIndex: 999,
    display: 'flex',
    flexDirection: 'row',
    width: '85%',
    flexWrap: 'wrap',
  },
  closeIcon: {
    width: 20,
    height: 20,
  },
  chipLabel: {
    position: 'absolute',
    backgroundColor: 'white',
    left: 6,
    paddingStart: 5,
    paddingEnd: 5,
    paddingHorizontal: 1,
    zIndex: 999,
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  vitalHistoryTextReason: {
    color: COLORS.text,
    fontSize: isHpTablet('1.6%'),
    fontFamily: FONTS.SFProDisplaySemibold,
    fontWeight: '600',
    lineHeight: hp('1.8%'),
    marginVertical: hp('1%'),
  },
  vitalHistoryTextTaken: {
    color: COLORS.text,
    fontSize: isHpTablet('1.5%'),
    fontFamily: FONTS.SFProDisplayRegular,
    fontWeight: '600',
    lineHeight: hp('1.8%'),
    marginBottom: hp('1%'),
  },
  vitalHistoryTextDate: {
    color: '#9A9FA4',
    fontSize: isHpTablet('1.4%'),
    fontFamily: FONTS.SFProDisplayRegular,
    lineHeight: hp('1.8%'),
    marginBottom: hp('1%'),
  },
  comparsionTrend: {
    fontFamily: FONTS.SFProDisplaySemibold,
    color: COLORS.text,
    fontSize: isHpTablet('1.8%'),
  },
  selectTextTouch: {
    display: 'flex',
    flexDirection: 'row',
    maxWidth: '50%',
    borderWidth: 1,
    paddingHorizontal: 4,
    borderRadius: 8,
    borderColor: '#E0E0E0',
  },
  selectText: {
    fontFamily: FONTS.SFProDisplayRegular,
    color: COLORS.text,
    fontSize: isHpTablet('1.4%'),
    marginHorizontal: 5,
  },
});
