import { StyleSheet } from 'react-native';
import { SIZES, COLORS, FONTS } from '../constants';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
import { isHpTablet } from '../hooks/useDeviceCheck';

export default StyleSheet.create({
  topBarTitle: {
    marginRight: hp('4.5%'),
    fontSize: isHpTablet(2.2),
    fontWeight: '700',
    color: '#207DFF',
    fontFamily: FONTS.SFProDisplayBold,
  },
  addPadding: { padding: 1 },
  cardTitle: {
    fontFamily: FONTS.SFProDisplaySemibold,
    color: '#00A807',
    fontSize: isHpTablet('1.2%'),
    fontStyle: 'normal',
    fontWeight: '600',
    letterSpacing: 0.3,
  },

  card: {
    width: SIZES.screenWidth / 1.2,
    borderRadius: SIZES.padding,
  },
  container: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: COLORS.white,
  },
  headerContainer: {
    height: 50,
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
    width: SIZES.screenWidth,
    paddingHorizontal: isHpTablet('2.2%'),
  },
  headerColumn: {
    flex: 0.2,
    alignItems: 'center',
    flexDirection: 'row',
  },
  divider: {
    borderBottomWidth: 2,
    borderColor: COLORS.grey_E5E5E5,
    marginVertical: 15,
  },
  imageFrameStyle: {
    marginTop: 10,
    width: SIZES.screenWidth / 1.12,
    height: SIZES.screenWidth * 0.4,
    alignSelf: 'center',
    borderRadius: 10,
    marginBottom: 10,
  },
  doctorFrame: {
    // marginTop: 10,
    alignSelf: 'center',
  },
  expolreFrame: {
    marginTop: 10,
    width: SIZES.screenWidth,
    height: 200,
    alignSelf: 'center',
  },
  doctorImage: {
    marginTop: 10,
    // width: 54,
    height: isHpTablet('8%'),
    width: isHpTablet('8%'),
    // height: 54,
    alignSelf: 'center',
  },
  doctorName: {
    justifyContent: 'center',
    textAlign: 'center',
    fontSize: isHpTablet('1.4%'),
    marginTop: isHpTablet('0.5%'),
    fontFamily: FONTS.SFProDisplayMedium,
    color: COLORS.text,
  },
  doctorDesination: {
    justifyContent: 'center',
    textAlign: 'center',
    fontSize: isHpTablet('1.2%'),
    fontFamily: FONTS.SFProDisplayRegular,
    color: COLORS.black,
  },
  doctorConsultText: {
    fontFamily: FONTS.SFProDisplaySemibold,
    color: '#232323',
    fontSize: isHpTablet('1.6%'),
    fontStyle: 'normal',
    fontWeight: '600',
    letterSpacing: 0.3,
  },
  searchInput: {
    width: SIZES.screenWidth - 36,
    height: isHpTablet('5.5%'),
    marginVertical: 5,
    backgroundColor: 'white',
    marginTop: 15,
  },
  bookText: {
    justifyContent: 'center',
    textAlign: 'center',
    padding: 10,
    color: COLORS.text,
    fontSize: isHpTablet('1.6%'),
    fontFamily: FONTS.SFProDisplaySemibold,
  },
  bookBox: {
    width: '48%',
    height: '99%',
    borderWidth: 1,
    borderColor: '#EEEEEE',
    borderRadius: 10,
    backgroundColor: '#E0F0FF',
  },
  bookImage: { marginTop: 10, width: 110, height: 80, alignSelf: 'center' },
  bookSubBox: {
    width: '100%',
    height: '1%',
    backgroundColor: 'white',
    flex: 1,
    // borderBottomWidth: 1,
    borderBottomEndRadius: 10,
    borderBottomStartRadius: 10,
    borderColor: '#EEEEEE',
  },
  teleImage: {
    marginTop: 10,
    width: 110,
    height: 80,
    alignSelf: 'center',
  },
  teleBox: {
    width: '48%',
    height: '99%',
    borderWidth: 1,
    borderColor: '#EEEEEE',
    borderRadius: 10,
    backgroundColor: '#EEEEEE',
  },
  teleSubBox: {
    width: '100%',
    height: '10%',
    backgroundColor: 'white',
    flex: 1,
    borderBottomWidth: 1,
    borderBottomEndRadius: 10,
    borderBottomStartRadius: 10,
    borderColor: '#EEEEEE',
  },
  pharmacyBox: {
    width: SIZES.screenWidth / 3.65,
    height: '99%',
    borderWidth: 1,
    borderColor: '#EEEEEE',
    borderRadius: 10,
    backgroundColor: '#FAECFF',
  },
  pharmacyImage: { marginTop: 10, width: 72, height: 62, alignSelf: 'center' },
  labBox: {
    width: SIZES.screenWidth / 3.65,
    height: 102,
    borderWidth: 1,
    borderColor: '#EEEEEE',
    borderRadius: 10,
    backgroundColor: '#FAECFF',
  },
  labImage: { marginTop: 10, width: 50, height: 62, alignSelf: 'center' },
  vaccineBox: {
    width: SIZES.screenWidth / 3.65,
    height: 102,
    borderWidth: 1,
    borderColor: '#EEEEEE',
    borderRadius: 10,
    backgroundColor: '#E0F0FF',
  },
  vaccineTextBox: {
    backgroundColor: 'white',
    height: 29,
    borderBottomWidth: 1,
    borderBottomEndRadius: 10,
    borderBottomStartRadius: 10,
    borderColor: '#EEEEEE',
  },
  vaccineImage: { marginTop: 10, width: 72, height: 62, alignSelf: 'center' },
  vaccineText: {
    justifyContent: 'center',
    textAlign: 'center',
    padding: 1,
    width: '99%',
    color: COLORS.black,
    fontFamily: FONTS.SFProDisplaySemibold,
  },
  dropdown: {
    height: 45,
    width: SIZES.screenWidth - 45,
    borderColor: '#EDEDED',
    color: '#AEB2B3',
    borderWidth: 1,
    borderRadius: SIZES.padding,
    paddingHorizontal: 8,
  },
  icon: {
    marginHorizontal: 5,
  },
  label: {
    position: 'absolute',
    backgroundColor: COLORS.background.white,
    left: 10,
    top: -35,
    paddingHorizontal: 1,
    zIndex: 999,
    paddingStart: 5,
    paddingEnd: 5,
    fontSize: 12,
    color: COLORS.text,
  },
  placeholderStyle: {
    fontSize: 12,
    color: '#AEB2B3',
    fontFamily: FONTS.SFProDisplayRegular,
  },
  selectedTextStyle: {
    fontSize: 16,
  },
  iconStyle: {
    width: 20,
    height: 20,
  },
  inputSearchStyle: {
    height: 40,
    // fontSize: 16,
    fontSize: hp('5%'),
  },
  backgroundStyle: {
    backgroundColor: COLORS.white,
    borderColor: COLORS.gray,
    borderWidth: 2,
  },
  inputTxtStyle: {
    width: wp('90%'),
    height: isHpTablet('5.5%'),
    fontSize: isHpTablet('1.8%'),
    lineHeight: isHpTablet('2%'),
    fontFamily: FONTS.SFProDisplayBold,
    backgroundColor: COLORS.white,
  },
  searchDoctorInput: {
    marginTop: 15,
  },
  appointMainBox: {
    width: '48%',
    backgroundColor: 'white',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#EEEEEE',
    borderRadius: 10,
  },
  iconHeight: { height: isHpTablet('2%') },
});
