import { StyleSheet } from 'react-native';
import { COLORS, FONTS, SIZES } from '../constants';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
import { isHpTablet, isWpTablet } from '../hooks/useDeviceCheck';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.white,
  },
  header: {
    justifyContent: 'center',
    paddingVertical: isHpTablet(1),
    borderBottomColor: COLORS.white_smoke,
    borderBottomWidth: 1,
  },
  topBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: hp('1.5%'),
    paddingVertical: hp('0.7%'),
  },
  topBarTitle: {
    ...FONTS.h5,
    color: COLORS.black_231F20,
    justifyContent: 'center',
    fontWeight: '700',
    textAlign: 'center',
  },
  icon: {
    height: 22,
    width: 22,
    justifyContent: 'center',
  },
  boxFlexStyle: {
    flex: 1,
  },
  scrollViewStyle: { marginHorizontal: 20 },
  ScrollViewStyle: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  notFoundTextStyle: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  yearMarginStyle: {
    marginLeft: isWpTablet('3.5%'),
    marginBottom: 10,
    fontSize: isHpTablet('1.6%'),
    fontFamily: FONTS.Inter,
    fontWeight: '500',
    color: COLORS.black_2D3339,
  },
  accountBoxIconStyle: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginHorizontal: 22,
  },
  accountIconStyle: {
    marginTop: 5,
    marginHorizontal: 4,
    alignSelf: 'center',
  },
  accNameStyle: {
    marginTop: 5,
    fontSize: isHpTablet('1.6%'),
    fontFamily: FONTS.Inter,
    color: COLORS.black,
  },
  listContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    marginVertical: 5,
  },
  cardContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    width: '100%',
  },
  card: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    height: isWpTablet('20%'),
    borderBottomWidth: 1,
    borderColor: COLORS.grey_E5E5E5,
    marginHorizontal: isHpTablet('1.5%'),
    width: '90%',
  },
  cardContent: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    flexGrow: 1,
    width: '77%',
  },
  cardTitleStyle: {
    fontFamily: FONTS.SFProDisplayBold,
    fontSize: isHpTablet('1.8%'),
    lineHeight: isHpTablet('2%'),
    color: COLORS.text,
    fontWeight: '600',
    marginTop: hp('1%'),
  },
  nameStyle: {
    fontFamily: FONTS.Inter,
    fontSize: isHpTablet('1.4%'),
    lineHeight: isHpTablet('1.5%'),
    color: COLORS.darkBlue,
    fontStyle: 'normal',
    fontWeight: '400',
    marginTop: hp('1%'),
  },
  billNoStyle: {
    fontFamily: FONTS.Inter,
    textTransform: 'capitalize',
    fontSize: isHpTablet('1.6%'),
    color: COLORS.background.primary,
    fontWeight: '400',
    marginTop: hp('0.8%'),
  },
  recNoStyle: {
    fontFamily: FONTS.Inter,
    fontSize: isHpTablet('1.6%'),
    color: COLORS.background.primary,
    fontWeight: '400',
    marginBottom: 8,
  },
  iconSpace: {
    width: isWpTablet('6%'),
    height: isHpTablet('6%'),
    marginTop: hp('1.2%'),
  },
  billBoxStyle: {
    display: 'flex',
    width: '10%',
  },
  dayBoxStyle: {
    backgroundColor: COLORS.text,
    borderRadius: isHpTablet('3%'),
    height: isHpTablet('4%'),
    width: isHpTablet('4%'),
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: '7%',
  },
  monthStyle: {
    fontFamily: FONTS.Inter,
    fontSize: isHpTablet('1.2%'),
    // textAlign: 'center',
    marginLeft: isHpTablet('0.8%'),
    color: COLORS.placeHolder,
    fontWeight: '400',
    marginTop: 5,
  },
  separator: {
    marginLeft: isHpTablet('1.8%'),
    marginVertical: 5,
    height: hp('5%'),
    width: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dayStyle: {
    color: 'white',
    fontSize: isHpTablet('1.4%'),
    fontWeight: '500',
    fontFamily: FONTS.Inter,
  },
  backgroundStyle: {
    backgroundColor: COLORS.white,
    borderColor: COLORS.gray,
    borderWidth: 1,
  },
  addIcon: {
    height: 20,
    width: 20,
  },
  menuBsLayout: {
    width: '100%',
  },
  flexRow: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    marginTop: 10,
    marginHorizontal: 20,
  },
  filterIcon: {
    alignItems: 'center',
    height: 14,
    width: 14,
  },
  justifyStyle: {
    justifyContent: 'center',
  },
  content: {
    flex: 1,
  },
  inputTxtStyle: {
    width: SIZES.screenWidth * 0.9,
    height: isHpTablet('5.5%'),
    backgroundColor: COLORS.white,
    fontFamily: FONTS.SFProDisplayRegular,
    fontSize: isHpTablet('1.6%'),
    lineHeight: isHpTablet('2%'),
  },
  inputDisableTxtStyle: {
    width: SIZES.screenWidth * 0.9,
    height: isHpTablet('5.5%'),
    backgroundColor: COLORS.white_smoke,
    fontFamily: FONTS.SFProDisplayRegular,
    fontSize: isHpTablet('1.6%'),
    lineHeight: isHpTablet('2%'),
  },
  topDivider: {
    borderBottomWidth: 1,
    borderColor: COLORS.grey_E5E5E5,
    marginTop: '10%',
  },
  typeContainer: {
    marginVertical: hp('1.5%'),
    width: '100%',
  },
  typeLabel: {
    color: COLORS.text,
    fontFamily: FONTS.SFProDisplayRegular,
    fontSize: isHpTablet('1.6%'),
    marginTop: hp('0.5%'),
    marginHorizontal: hp('3%'),
  },
  typeFlex: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: '7%',
    width: '100%',
  },
  typeFlexItem: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    width: '25%',
  },
  typeTitLabel: {
    color: '#8A8A8A',
    fontFamily: FONTS.SFProDisplayRegular,
    fontSize: isHpTablet('1.7%'),
    marginTop: '5%',
  },
  middleDivider: {
    borderBottomWidth: 1,
    borderColor: COLORS.grey_E5E5E5,
  },
  createdOnCnt: {
    marginHorizontal: hp('1%'),
    marginVertical: hp('2%'),
    alignItems: 'center',
  },
  bottomContainer: {
    flex: 1,
    width: '100%',
    backgroundColor: '#F8F8F8',
  },
  boxStyle: {
    height: 250,
  },
  applyBtnStyle: {
    width: '100%',
    height: isHpTablet('6.5%'),
    backgroundColor: COLORS.background.primary,
    borderRadius: isHpTablet('1%'),
  },
  applyTxtStyle: {
    fontFamily: FONTS.SFProDisplaySemibold,
    fontSize: isHpTablet('2%'),
    lineHeight: isHpTablet('2.2%'),
    color: COLORS.background.white,
    textAlign: 'center',
  },
  buttonBoxContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginVertical: 10,
    marginHorizontal: 20,
  },
  titleContainer: {
    marginTop: '5%',
  },
  filesContainer: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: '90%',
    marginVertical: hp('1%'),
    marginHorizontal: '6%',
  },
  addFile: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    width: hp('9%'),
    height: hp('9%'),
    borderRadius: 7,
    backgroundColor: '#E7E7E7',
    marginHorizontal: '2%',
    marginVertical: 10,
  },
  imgPreview: {
    width: hp('9%'),
    height: hp('9%'),
    marginHorizontal: '2%',
    marginVertical: 10,
  },
  plusText: {
    fontFamily: FONTS.SFProDisplaySemibold,
    fontSize: isHpTablet('1.8%'),
    color: COLORS.black,
    textAlign: 'center',
  },
  addText: {
    fontFamily: FONTS.SFProDisplaySemibold,
    fontSize: isHpTablet('1.6%'),
    color: COLORS.black,
    marginHorizontal: hp('0.2%'),
    textAlign: 'center',
  },
  typeBtnStyle: {
    width: '100%',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  typeActTitLabel: {
    color: COLORS.background.primary,
    fontFamily: FONTS.SFProDisplayRegular,
    fontSize: 13,
    marginTop: '5%',
  },
  pdfContainer: {
    justifyContent: 'flex-start',
    alignItems: 'center',
    width: hp('9%'),
    height: hp('9%'),
    marginHorizontal: '2%',
    marginVertical: 10,
  },
  pdfStyle: {
    width: '100%',
    height: '100%',
    borderRadius: 5,
  },
  fileImage: {
    width: '100%',
    height: '100%',
    borderRadius: 5,
    resizeMode: 'contain',
  },
  bottomSheetContainer: {
    height: '100%',
    display: 'flex',
    justifyContent: 'center',
    marginTop: 10,
    backgroundColor: COLORS.white,
  },
  title: {
    fontSize: isHpTablet('1.8%'),
    lineHeight: isHpTablet('2%'),
    color: '#232323',
    paddingVertical: 5,
    paddingHorizontal: 10,
  },
  bsItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingVertical: isHpTablet('2%'),
    backgroundColor: COLORS.white,
  },
  divider: {
    borderBottomWidth: 1,
    borderColor: COLORS.grey_E5E5E5,
  },
  contentMediView: {
    marginVertical: hp('1.2%'),
    // marginHorizontal: hp('2%'),
    flexGrow: 1,
  },
  year: {
    fontSize: isHpTablet('1.8%'),
    fontFamily: FONTS.SFProDisplayMedium,
    color: '#C7C7C7',
  },
  date: {
    fontSize: isHpTablet('1.6%'),
    fontFamily: FONTS.SFProDisplayMedium,
    color: '#232323',
    paddingTop: hp('1.5%'),
  },
  recordTxt: {
    fontSize: isHpTablet('1.9%'),
    fontFamily: FONTS.SFProDisplayBold,
    fontWeight: '600',
    color: '#232323',
    paddingVertical: hp('0.5%'),
  },
  countType: {
    fontFamily: FONTS.Inter,
    textTransform: 'capitalize',
    fontSize: isHpTablet('1.6%'),
    color: COLORS.background.primary,
    fontWeight: '400',
    marginTop: hp('0.3%'),
  },
  container1: {
    paddingVertical: isHpTablet('1%'),
    paddingHorizontal: hp('1.5%'),
    height: isWpTablet('30%'),
    borderBottomWidth: 1,
    borderBottomColor: COLORS.white_smoke,
  },
  container2: {
    paddingVertical: 5,
  },
  fileHeader: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    height: hp('3%'),
    paddingHorizontal: hp('1.5%'),
  },
  fileTitle: {
    fontFamily: FONTS.SFProDisplayMedium,
    textTransform: 'capitalize',
    color: '#232323',
    fontSize: isHpTablet('1.8%'),
    marginHorizontal: hp('0.1%'),
    fontWeight: '400',
    flexGrow: 1,
  },
  menuIcon: {
    width: 15,
    height: 15,
  },
  fileContainer: {
    width: '100%',
    // height: 160,
    height: hp('18%'),
    backgroundColor: '#F2F2F2',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    marginVertical: 10,
  },
  pdfContainerView: {
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: '100%',
    marginHorizontal: 10,
  },
  imageContainer: {
    width: '100%',
    height: '100%',
    backgroundColor: '#F2F2F2',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  image: {
    width: '50%',
    height: '100%',
    resizeMode: 'cover',
  },
});
