import { StyleSheet } from 'react-native';
import { COLORS, FONTS, SIZES } from '../../constants';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
import { isHpTablet } from '../../hooks/useDeviceCheck';

export default StyleSheet.create({
  container: {
    height: '100%',
    justifyContent: 'center',
  },
  boxContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: hp('2%'),
  },
  buttonBoxContainer: {
    marginTop: hp('1%'),
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  boxStyle: {
    height: hp('25%'),
  },
  applyBtnStyle: {
    backgroundColor: COLORS.background.primary,
    borderRadius: 10,
    height: isHpTablet('6.5%'),
    width: '45%',
  },
  applyTxtStyle: {
    color: COLORS.background.white,
    fontSize: isHpTablet('1.8%'),
    fontWeight: '600',
    fontFamily: FONTS.SFProDisplaySemibold,
  },
  clearBtnStyle: {
    backgroundColor: COLORS.background.white,
    borderColor: COLORS.background.primary,
    borderWidth: 2,
    borderRadius: 10,
    height: isHpTablet('6.5%'),
    width: '45%',
  },
  clearTxtStyle: {
    color: COLORS.text,
    fontSize: isHpTablet('1.8%'),
    fontWeight: '600',
    fontFamily: FONTS.SFProDisplaySemibold,
  },
  divider: {
    // marginTop: hp('1%'),
  },
  itemStyle: {
    height: isHpTablet('7%'),
    borderBottomWidth: 1,
    justifyContent: 'center',
    borderBottomColor: COLORS.grey_E5E5E5,
  },
  selectedRadioText: {
    color: COLORS.background.primary,
    fontFamily: FONTS.SFProDisplayRegular,
    fontSize: isHpTablet('2%'),
    // marginTop: isHpTablet('1.5%'),
  },
  dosageInputTxt: {
    height: isHpTablet('5.5%'),
    marginVertical: hp('0.5%'),
    backgroundColor: 'white',
    borderRadius: 8,
    fontFamily: FONTS.SFProDisplayRegular,
    fontSize: isHpTablet('2%'),
  },
  searchDoctorInput: {
    marginTop: hp('1.5%'),
  },
  advanceButtonBoxContainer: {
    marginTop: hp('4%'),
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: hp('2%'),
  },
  advanceApplyBtnStyle: {
    width: '100%',
    height: isHpTablet('6.5%'),
    backgroundColor: COLORS.background.primary,
    borderRadius: 10,
  },

  daysBoxText: {
    fontSize: isHpTablet('1.4%'),
    color: COLORS.black,
    marginHorizontal: hp('2%'),
    fontFamily: FONTS.SFProDisplayRegular,
  },
  selectedDaysBoxText: {
    fontSize: isHpTablet('1.4%'),
    color: COLORS.white,
    marginHorizontal: hp('0.4%'),
    fontFamily: FONTS.SFProDisplayRegular,
  },
  daysBox: {
    flexDirection: 'row',
    alignItems: 'center',
    margin: hp('0.5%'),
    borderRadius: 4,
    borderWidth: 1,
    borderColor: 'rgba(244, 244, 244, 0.6)',
    backgroundColor: 'rgba(244, 244, 244, 0.6)',
    height: hp('4.5%'),
    width: wp('30%'),
    paddingHorizontal: hp('0.6%'),
  },
  selectedDaysBox: {
    flexDirection: 'row',
    alignItems: 'center',
    margin: hp('0.5%'),
    borderRadius: 4,
    borderWidth: 1,
    backgroundColor: COLORS.background.primary,
    borderColor: COLORS.background.primary,
    height: hp('4.5%'),
    width: wp('30%'),
    paddingHorizontal: hp('0.6%'),
  },
  selectDurationBox: {
    backgroundColor: 'rgba(244, 244, 244, 0.6)',
    // marginTop: 10,
    height: isHpTablet('5%'),
    // marginBottom: 10,
  },
  mariginStyle: {
    marginTop: isHpTablet('1.2%'),
    marginHorizontal: hp('1.8%'),
    fontFamily: FONTS.SFProDisplayMedium,
    fontSize: isHpTablet('1.5%'),
    color: COLORS.text,
  },
  scrollPickerText: {
    fontFamily: FONTS.SFProDisplayRegular,
    fontSize: isHpTablet('1.8%'),
  },
  maediImage: {
    marginHorizontal: hp('1%'),
  },
  adviceMediBox: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: hp('3%'),
  },
  numberBox: {
    height: hp('10%'),
    width: wp('20%'),
    marginHorizontal: hp('3%'),
  },
  dayweekBox: {
    height: hp('10%'),
    width: wp('30%'),
    marginHorizontal: hp('3%'),
  },
  timeNumberBox: {
    height: hp('15%'),
    width: wp('20%'),
    marginHorizontal: hp('3%'),
  },
  timeDayweekBox: {
    height: hp('15%'),
    width: wp('30%'),
    marginHorizontal: hp('3%'),
  },
  adviceMarginTop: { height: hp('2%') },
  scrollPickerStyles: {
    height: hp('15%'),
    itemHeight: hp('5%'),
    highlightBorderWidth: hp('0.2%'),
  },
  scheduleContainer: {
    justifyContent: 'space-between',
  },
  scheduleBoxContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
  },
  scheduleButtonBoxContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginVertical: hp('2%'),
  },

  scheduleApplyBtnStyle: {
    width: '100%',
    height: isHpTablet('6.5%'),
    backgroundColor: COLORS.background.primary,
    borderRadius: 10,
  },
  scheduleSelectDurationBox: {
    backgroundColor: 'rgba(244, 244, 244, 0.6)',
    // marginTop: 10,
    height: isHpTablet('5%'),
    marginVertical: hp('2%'),
    // marginBottom: 10,
  },
  scheduleApplyTxtStyle: {
    color: COLORS.background.secondary,
    fontSize: isHpTablet('2%'),
    fontFamily: FONTS.SFProDisplaySemibold,
  },
  scheduleDivider: {
    borderBottomWidth: 1,
    borderColor: COLORS.grey_E5E5E5,
    marginTop: 10,
  },
  scheduleDaysBoxText: {
    fontSize: isHpTablet('1.2%'),
    color: COLORS.placeHolder,
    fontFamily: FONTS.SFProDisplayRegular,
    marginHorizontal: hp('1.15%'),
  },
  scheduleSelectedDaysBoxText: {
    fontSize: isHpTablet('1.2%'),
    color: COLORS.white,
    fontFamily: FONTS.SFProDisplayRegular,
    marginHorizontal: hp('1.1%'),
  },
  scheduleDaysBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    margin: hp('0.4%'),
    borderRadius: 4,
    borderWidth: 1,
    borderColor: COLORS.ligth_gray,
    height: hp('5%'),
    width: wp('10.5%'),
    backgroundColor: COLORS.ligth_gray,
  },
  scheduleSelectedDaysBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    margin: hp('0.5%'),
    borderRadius: 4,
    borderWidth: 1,
    backgroundColor: COLORS.background.primary,
    borderColor: COLORS.background.primary,
    height: hp('5%'),
    width: wp('10.5%'),
  },
  scheduleMarginTopStyle: {
    marginTop: 5,
    // marginHorizontal: 20,
    fontSize: isHpTablet('1.2%'),
    fontFamily: FONTS.SFProDisplayMedium,
    color: COLORS.black,
  },
  boxBoderStyle: { borderBottomWidth: 1, borderColor: COLORS.grey_E5E5E5, width: wp('30%') },
  inputStyle: {
    width: wp('30%'),
    textAlign: 'center',
    borderBottomWidth: 1,
    borderBottomColor: COLORS.white_smoke,
  },
  scheduleScrollPickerText: {
    fontFamily: FONTS.SFProDisplayRegular,
    fontSize: isHpTablet('1.4%'),
  },
  everyDayText: {
    color: COLORS.background.primary,
    fontFamily: FONTS.SFProDisplayRegular,
    fontSize: isHpTablet('1.6%'),
  },
  intervalDaysBox: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: hp('8%'),
    marginTop: hp('3%'),
    marginBottom: hp('1%'),
  },
  specificDayBox: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: hp('1.5%'),
    alignItems: 'center',
    marginTop: hp('2%'),
  },
  filterBoxStyle: {
    height: hp('24%'),
  },
  filterApplyBtnStyle: {
    backgroundColor: COLORS.background.primary,
    borderRadius: 10,
    width: '100%',
    height: isHpTablet('6.5%'),
  },
  filterApplyTxtStyle: {
    color: COLORS.background.secondary,
    fontSize: isHpTablet('2%'),
    fontWeight: '600',
    fontFamily: FONTS.SFProDisplaySemibold,
  },
  textStyle: {
    width: 100,
    height: 40,
  },
});
